[config]
schemaVersion = "0.0.1"

[general]
repository = "https://thunderstore.io"

[package]
namespace = "www_Day_Dream"
name = "WiresSimulationFix"
description = "Removes the LOD factor on the `requiredDeltaTicks` inside the SimulationGraph::Update."
containsNsfwContent = false
[package.dependencies]
BepInEx-BepInExPack = "5.4.2100"

[build]
icon = "icon.png"
readme = "../README.md"
outdir = "../dist"

[[build.copy]]
source = "../CHANGELOG.md"
target = "/"
[[build.copy]]
source = "../WiresSimulationFix/bin/Release/netstandard2.1/wwwDayDream.WiresSimulationFix.dll"
target = "/BepInEx/plugins/WiresSimulationFix/"
[[build.copy]]
source = "../WiresSimulationFix/bin/Release/netstandard2.1/FSharp.Core.dll"
target = "/BepInEx/core/"
[[build.copy]]
source = "../LICENSE"
target = "/BepInEx/plugins/WiresSimulationFix/"

[publish]
communities = [ "shapez-2" ]
[publish.categories]
shapez-2 = [ "mods" ]
